/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaze
 */
public class DialogoStock extends javax.swing.JDialog {
    /**
     * Creates new form DialogoStock
     */
    public DialogoStock(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        clases.SOGECOMA.ModeloTablaStock.setRowCount(0);
        clases.SOGECOMA.ModeloTablaStock.setColumnCount(0);
        tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
        clases.CargarTablas carTab=new clases.CargarTablas();
        carTab.cargarTablaStock(false,false);
        tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
        clases.ColorearTablas ColTab = new clases.ColorearTablas(2,3);
        tablaStock.setDefaultRenderer (Object.class, ColTab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaStock = new javax.swing.JTable();
        cmdSeleccionarMarerial = new javax.swing.JButton();
        txtMaterial = new javax.swing.JTextField();
        cmdMinimos = new javax.swing.JButton();
        cmdTodo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaStock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaStock);

        cmdSeleccionarMarerial.setText("Buscar Material");
        cmdSeleccionarMarerial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarMarerialActionPerformed(evt);
            }
        });

        txtMaterial.setEditable(false);

        cmdMinimos.setText("Mostrar Stocks Bajo Mínimos");
        cmdMinimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinimosActionPerformed(evt);
            }
        });

        cmdTodo.setText("Mostrar Todo");
        cmdTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdMinimos, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdTodo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSeleccionarMarerial, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaterial)
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSeleccionarMarerial)
                    .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdMinimos)
                    .addComponent(cmdTodo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSeleccionarMarerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarMarerialActionPerformed
        try {
            ventanas.DialogoSelectorMaterial selMat = new DialogoSelectorMaterial(null,true);
            selMat.setVisible(true);
            txtMaterial.setText(clases.SOGECOMA.nomMaterial);
            clases.SOGECOMA.ModeloTablaStock.setRowCount(0);
            clases.SOGECOMA.ModeloTablaStock.setColumnCount(0);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
            clases.CargarTablas carTab = new clases.CargarTablas();
            carTab.cargarTablaStock(true,false);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSeleccionarMarerialActionPerformed

    private void cmdMinimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinimosActionPerformed
        try {
            clases.SOGECOMA.ModeloTablaStock.setRowCount(0);
            clases.SOGECOMA.ModeloTablaStock.setColumnCount(0);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
            clases.CargarTablas carTab = new clases.CargarTablas();
            carTab.cargarTablaStock(false,true);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
            txtMaterial.setText(null);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdMinimosActionPerformed

    private void cmdTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTodoActionPerformed
        try {
            clases.SOGECOMA.ModeloTablaStock.setRowCount(0);
            clases.SOGECOMA.ModeloTablaStock.setColumnCount(0);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
            clases.CargarTablas carTab = new clases.CargarTablas();
            carTab.cargarTablaStock(false,false);
            tablaStock.setModel(clases.SOGECOMA.ModeloTablaStock);
            txtMaterial.setText(null);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdTodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    DialogoStock dialog = new DialogoStock(new javax.swing.JFrame(), true);
                    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                        @Override
                        public void windowClosing(java.awt.event.WindowEvent e) {
                            System.exit(0);
                        }
                    });
                    dialog.setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(DialogoStock.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdMinimos;
    private javax.swing.JButton cmdSeleccionarMarerial;
    private javax.swing.JButton cmdTodo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaStock;
    private javax.swing.JTextField txtMaterial;
    // End of variables declaration//GEN-END:variables
}
