/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaze
 */
public class DialogoControlMaterial extends javax.swing.JDialog {
    private PanelTodosItems ti;
    private PanelTotalComprado tc;
    private PanelBuscarBloque bb;
    private PanelBuscarItem bi;
    private PanelBuscarMaterial bm;
    private PanelComparativaConsumo cc;
    private PanelBuscarItemEnTodos it;
    
    private void borrarPaneles(){
        try{
            this.remove(ti);
        }catch (Exception e){}
        
        try{
            this.remove(tc);
        }catch (Exception e){}
        
        try{
            this.remove(bb);
        }catch (Exception e){}
        
        try{
            this.remove(bi);
        }catch (Exception e){}
        
        try{
            this.remove(bm);
        }catch (Exception e){}
        try{
            this.remove(cc);
        }catch (Exception e){}
        try{
            this.remove(it);
        }catch (Exception e){}
    }
    /**
     * Creates new form DialogoVerMaterial
     */
    public DialogoControlMaterial(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLayout(new FlowLayout());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVistasGenerales = new javax.swing.JMenu();
        mnuItemEnTodos = new javax.swing.JMenuItem();
        mnuVerTotalComprado = new javax.swing.JMenuItem();
        mnuBuscarPor = new javax.swing.JMenu();
        mnuBuscarBloque = new javax.swing.JMenuItem();
        mnuBuscarItem = new javax.swing.JMenuItem();
        mnuBuscarMaterial = new javax.swing.JMenuItem();
        mnuComparativas = new javax.swing.JMenu();
        mnuComparativaMaterial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Control de Materiales");

        mnuVistasGenerales.setText("Vistas generales");

        mnuItemEnTodos.setText("Ver un Item, con sumatoria de todos los bloques");
        mnuItemEnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemEnTodosActionPerformed(evt);
            }
        });
        mnuVistasGenerales.add(mnuItemEnTodos);

        mnuVerTotalComprado.setText("Ver totales comprados por material");
        mnuVerTotalComprado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerTotalCompradoActionPerformed(evt);
            }
        });
        mnuVistasGenerales.add(mnuVerTotalComprado);

        jMenuBar1.add(mnuVistasGenerales);

        mnuBuscarPor.setText("Buscar por...");

        mnuBuscarBloque.setText("Buscar por bloque");
        mnuBuscarBloque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarBloqueActionPerformed(evt);
            }
        });
        mnuBuscarPor.add(mnuBuscarBloque);

        mnuBuscarItem.setText("Buscar por ítem");
        mnuBuscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarItemActionPerformed(evt);
            }
        });
        mnuBuscarPor.add(mnuBuscarItem);

        mnuBuscarMaterial.setText("Buscar por material");
        mnuBuscarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBuscarMaterialActionPerformed(evt);
            }
        });
        mnuBuscarPor.add(mnuBuscarMaterial);

        jMenuBar1.add(mnuBuscarPor);

        mnuComparativas.setText("Comparativas");

        mnuComparativaMaterial.setText("Comparar consumo de material entre bloques, por ítem");
        mnuComparativaMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComparativaMaterialActionPerformed(evt);
            }
        });
        mnuComparativas.add(mnuComparativaMaterial);

        jMenuBar1.add(mnuComparativas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuVerTotalCompradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerTotalCompradoActionPerformed
        borrarPaneles();
        try {
            tc=new PanelTotalComprado();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoControlMaterial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoControlMaterial.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.add(tc, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuVerTotalCompradoActionPerformed

    private void mnuBuscarBloqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarBloqueActionPerformed
        borrarPaneles();
        ti=new PanelTodosItems();
        this.add(ti, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuBuscarBloqueActionPerformed

    private void mnuBuscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarItemActionPerformed
        borrarPaneles();
        bi=new PanelBuscarItem();
        this.add(bi, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuBuscarItemActionPerformed

    private void mnuBuscarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBuscarMaterialActionPerformed
        borrarPaneles();
        bm=new PanelBuscarMaterial();
        this.add(bm, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuBuscarMaterialActionPerformed

    private void mnuComparativaMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComparativaMaterialActionPerformed
        borrarPaneles();
        cc=new PanelComparativaConsumo();
        this.add(cc, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuComparativaMaterialActionPerformed

    private void mnuItemEnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemEnTodosActionPerformed
        borrarPaneles();
        it=new PanelBuscarItemEnTodos();
        this.add(it, BorderLayout.CENTER);
        //Hacemos que el JFrame tenga el tamaño de todos sus elementos
        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_mnuItemEnTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoControlMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoControlMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoControlMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoControlMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoControlMaterial dialog = new DialogoControlMaterial(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuBuscarBloque;
    private javax.swing.JMenuItem mnuBuscarItem;
    private javax.swing.JMenuItem mnuBuscarMaterial;
    private javax.swing.JMenu mnuBuscarPor;
    private javax.swing.JMenuItem mnuComparativaMaterial;
    private javax.swing.JMenu mnuComparativas;
    private javax.swing.JMenuItem mnuItemEnTodos;
    private javax.swing.JMenuItem mnuVerTotalComprado;
    private javax.swing.JMenu mnuVistasGenerales;
    // End of variables declaration//GEN-END:variables
}
