/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;

/**
 *
 * @author Kaze
 */
public class DialogoTransferencia extends javax.swing.JDialog {
    Boolean esNuevo=true;    
    Boolean habilitar=false;
    /**
     * Creates new form DialogoTransferencia
     */
    private void cargarDatos(){
        if (clases.SOGECOMA.cargarDatos){
            txtFecha.setText(clases.SOGECOMA.fechaHoraTrans.substring(0, 10));
            try{
                txtHora.setText(clases.SOGECOMA.fechaHoraTrans.substring(11,16));
            }catch(Exception e){
                txtHora.setText(clases.SOGECOMA.fechaHoraTrans.substring(11,15));
            }
            txtMaterial.setText(clases.SOGECOMA.nomMaterial);
            txtUnidad.setText(clases.SOGECOMA.udMaterial);
            txtCantidad.setText(String.valueOf(clases.SOGECOMA.cantTrans));
//            txtContratistaOrigen.setText(clases.SOGECOMA.contratistaEnt);
            txtCodigoItemOrigen.setText(clases.SOGECOMA.numItemOrigen);
            txtNombreItemOrigen.setText(clases.SOGECOMA.nomItemOrigen);
            cboBloqueOrigen.setSelectedItem(clases.SOGECOMA.bloqueOrigen);
//            txtContratistaDestino.setText(clases.SOGECOMA.contratistaEnt);
            txtCodigoItemDestino.setText(clases.SOGECOMA.numItemDestino);
            txtNombreItemDestino.setText(clases.SOGECOMA.nomItemDestino);
            cboBloqueDestino.setSelectedItem(clases.SOGECOMA.bloqueDestino);
            cmdGuardar.setVisible(false);
            habilitar=false;
        }else{
            cmdModificar.setVisible(false);
            cmdEliminar.setVisible(false);
            habilitar=true;
        }
    }
    private void habilitarDeshabilitar(Boolean b){
        txtFecha.setEditable(b);
        txtHora.setEditable(b);
        cboBloqueOrigen.setEnabled(b);
        cboBloqueDestino.setEnabled(b);
        cmdSeleccionarMaterial.setEnabled(b);
        cmdSeleccionarItemOrigen.setEnabled(b);
        cmdSeleccionarItemDestino.setEnabled(b);
        txtCantidad.setEditable(b);
        txtContratistaOrigen.setEditable(b);
        txtContratistaDestino.setEditable(b);
    }
    public DialogoTransferencia(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        clases.FechaActual fecha=new clases.FechaActual();
        txtFecha.setText(fecha.obtenerFecha());
        cargarDatos();
        habilitarDeshabilitar(habilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboBloqueOrigen = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmdGuardar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        cmdModificar = new javax.swing.JButton();
        txtMaterial = new javax.swing.JTextField();
        cmdEliminar = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        txtUnidad = new javax.swing.JTextField();
        txtContratistaOrigen = new javax.swing.JTextField();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmdSeleccionarMaterial = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        txtNombreItemOrigen = new javax.swing.JTextField();
        cmdSeleccionarItemOrigen = new javax.swing.JButton();
        txtCodigoItemOrigen = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        cboBloqueDestino = new javax.swing.JComboBox();
        cmdSeleccionarItemDestino = new javax.swing.JButton();
        txtNombreItemDestino = new javax.swing.JTextField();
        txtCodigoItemDestino = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtContratistaDestino = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transferir Material Sobrante");
        setResizable(false);

        cboBloqueOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "Ñ", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "AA", "BB", "CC", "DD", "EE", "FF", "GG", "HH" }));
        cboBloqueOrigen.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboBloqueOrigenPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel1.setText("Fecha:");

        jLabel5.setText("Cantidad:");

        jLabel12.setText("Nombre del Ítem:");

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        jLabel11.setText("Código del Ítem de Origen:");

        jLabel6.setText("Nombre del Contratísta:");

        cmdModificar.setText("Modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        txtMaterial.setEditable(false);

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        txtUnidad.setEditable(false);

        txtContratistaOrigen.setEditable(false);

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));

        jLabel4.setText("Unidad:");

        jLabel3.setText("Material:");

        cmdSeleccionarMaterial.setText("Seleccionar Material");
        cmdSeleccionarMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarMaterialActionPerformed(evt);
            }
        });

        jLabel2.setText("Hora:");

        txtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        txtNombreItemOrigen.setEditable(false);

        cmdSeleccionarItemOrigen.setText("Seleccionar Ítem de Origen");
        cmdSeleccionarItemOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarItemOrigenActionPerformed(evt);
            }
        });

        txtCodigoItemOrigen.setEditable(false);

        jLabel9.setText("Bloque de Origen:");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cboBloqueDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "Ñ", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "AA", "BB", "CC", "DD", "EE", "FF", "GG", "HH" }));
        cboBloqueDestino.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboBloqueDestinoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmdSeleccionarItemDestino.setText("Seleccionar Ítem de Destino");
        cmdSeleccionarItemDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarItemDestinoActionPerformed(evt);
            }
        });

        txtNombreItemDestino.setEditable(false);

        txtCodigoItemDestino.setEditable(false);

        jLabel13.setText("Bloque de Destino:");

        jLabel15.setText("Nombre del Ítem:");

        jLabel16.setText("Código del Ítem dee Destino:");

        jLabel17.setText("Nombre del Contratísta:");

        txtContratistaDestino.setEditable(false);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("ORIGEN:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("DESTINO:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(jLabel20))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txtNombreItemOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel11)
                                                    .addGap(2, 2, 2)
                                                    .addComponent(txtCodigoItemOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel12))
                                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtContratistaOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cboBloqueOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6))
                                                .addComponent(cmdSeleccionarItemOrigen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGap(28, 28, 28)
                                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator8)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jLabel13)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(cboBloqueDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel17))
                                                    .addComponent(txtContratistaDestino)
                                                    .addComponent(cmdSeleccionarItemDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel16)
                                                        .addGap(2, 2, 2)
                                                        .addComponent(txtCodigoItemDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15))
                                                    .addComponent(txtNombreItemDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(124, 124, 124)
                                                .addComponent(jLabel21))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(168, 168, 168)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(86, 86, 86)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cmdSeleccionarMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(txtMaterial)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addComponent(jSeparator5))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmdSeleccionarMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cboBloqueOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(3, 3, 3)
                        .addComponent(txtContratistaOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdSeleccionarItemOrigen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtCodigoItemOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(2, 2, 2)
                        .addComponent(txtNombreItemOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cboBloqueDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(3, 3, 3)
                        .addComponent(txtContratistaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cmdSeleccionarItemDestino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodigoItemDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(7, 7, 7)
                        .addComponent(txtNombreItemDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdEliminar)
                    .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboBloqueOrigenPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboBloqueOrigenPopupMenuWillBecomeInvisible
        //Busca en el cuadro Contratístas el nombre del tío de este bloque y lo coloca en el cuadro de texto
        //Da valor a la variable ID_Contratista
        try{
            POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream("SOGECOMA.xls"));
            HSSFWorkbook libro = new HSSFWorkbook(fs);
            HSSFSheet cont = libro.getSheetAt(2);
            int numConts = cont.getLastRowNum();

            for (int c=1;c<=numConts;c++){
                if (cboBloqueOrigen.getSelectedItem().toString().equals(cont.getRow(c).getCell(1).getStringCellValue())){
                    clases.SOGECOMA.ID_Contratista= (int)cont.getRow(c).getCell(0).getNumericCellValue();
                    txtContratistaOrigen.setText(cont.getRow(c).getCell(2).getStringCellValue());
                }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_cboBloqueOrigenPopupMenuWillBecomeInvisible

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        clases.ValidacionCampos valCamp = new clases.ValidacionCampos();
        if(valCamp.validarCampos(txtCantidad.getText(), 2)&& valCamp.validarCampos(txtMaterial.getText(), 0)
            && valCamp.validarCampos(txtUnidad.getText(), 0) && valCamp.validarCampos(txtNombreItemOrigen.getText(), 0)
            && valCamp.validarCampos(txtCodigoItemOrigen.getText(), 0) && valCamp.validarCampos(txtContratistaOrigen.getText(), 0)){
                if (valCamp.validarCampos(txtHora.getText(), 3)){
                    try {
                        clases.SOGECOMA.cantTrans=Double.valueOf(txtCantidad.getText());
                        clases.SOGECOMA.bloqueOrigen=cboBloqueOrigen.getSelectedItem().toString();
                        clases.SOGECOMA.bloqueDestino=cboBloqueDestino.getSelectedItem().toString();
                        clases.SOGECOMA.fechaHoraTrans=txtFecha.getText()+" "+txtHora.getText();

                        if (esNuevo){
                            if (JOptionPane.showConfirmDialog(rootPane, 
                            "¿Desea Transferir "+txtCantidad.getText()+" "+txtUnidad.getText()+" de "+txtMaterial.getText()+
                            " \nDESDE el Item "+txtCodigoItemOrigen.getText()+" del bloque "+cboBloqueOrigen.getSelectedItem().toString()+
                            " \nAL Item "+txtCodigoItemDestino.getText()+" del bloque "+cboBloqueDestino.getSelectedItem().toString()+"? (Revise bien los datos)") == 0) {
                                clases.GuardarNuevaTransferencia guarTrans=new clases.GuardarNuevaTransferencia();
                                guarTrans.guardarTransferencia();
                            }
                        } else {
                            if (JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar esta Transferencia?") == 0) {
                                clases.ModificarEntrega modEnt=new clases.ModificarEntrega();
                                modEnt.modificarEntrega();
                            }
                        }
                        this.setVisible(false);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(DialogoNuevoContratista.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(DialogoNuevoContratista.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }else{
            txtCantidad.setText("");
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdSeleccionarMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarMaterialActionPerformed
        try {
            DialogoSelectorMaterial selMat = new DialogoSelectorMaterial(null,true);
            selMat.setVisible(true);
            txtMaterial.setText(clases.SOGECOMA.nomMaterial);
            txtUnidad.setText(clases.SOGECOMA.udMaterial);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSeleccionarMaterialActionPerformed

    private void cmdSeleccionarItemOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarItemOrigenActionPerformed
        try {
            DialogoSelectorItem selIt = new DialogoSelectorItem(null,true);
            selIt.setVisible(true);
            txtNombreItemOrigen.setText(clases.SOGECOMA.nomItem);
            txtCodigoItemOrigen.setText(clases.SOGECOMA.numItem);
//            clases.SOGECOMA.numItemOrigen=clases.SOGECOMA.numItem;
//            clases.SOGECOMA.nomItemOrigen=clases.SOGECOMA.nomItem;
            clases.SOGECOMA.ID_ItemOrigen=clases.SOGECOMA.ID_Item;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSeleccionarItemOrigenActionPerformed

    private void cboBloqueDestinoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboBloqueDestinoPopupMenuWillBecomeInvisible
        //Busca en el cuadro Contratístas el nombre del tío de este bloque y lo coloca en el cuadro de texto
        //Da valor a la variable ID_Contratista
        try{
            POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream("SOGECOMA.xls"));
            HSSFWorkbook libro = new HSSFWorkbook(fs);
            HSSFSheet cont = libro.getSheetAt(2);
            int numConts = cont.getLastRowNum();

            for (int c=1;c<=numConts;c++){
                if (cboBloqueDestino.getSelectedItem().toString().equals(cont.getRow(c).getCell(1).getStringCellValue())){
                    clases.SOGECOMA.ID_Contratista= (int)cont.getRow(c).getCell(0).getNumericCellValue();
                    txtContratistaDestino.setText(cont.getRow(c).getCell(2).getStringCellValue());
                }
            }
        }catch(Exception e){}
    }//GEN-LAST:event_cboBloqueDestinoPopupMenuWillBecomeInvisible

    private void cmdSeleccionarItemDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarItemDestinoActionPerformed
        try {
            DialogoSelectorItem selIt = new DialogoSelectorItem(null,true);
            selIt.setVisible(true);
            txtNombreItemDestino.setText(clases.SOGECOMA.nomItem);
            txtCodigoItemDestino.setText(clases.SOGECOMA.numItem);
//            clases.SOGECOMA.numItemDestino=clases.SOGECOMA.numItem;
//            clases.SOGECOMA.nomItemDestino=clases.SOGECOMA.nomItem; 
            clases.SOGECOMA.ID_ItemDestino=clases.SOGECOMA.ID_Item;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdSeleccionarItemDestinoActionPerformed

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        habilitarDeshabilitar(true);
        esNuevo = false;
        cmdModificar.setVisible(false);
        cmdEliminar.setVisible(false);
        cmdGuardar.setVisible(true);
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer ELIMINAR esta Transferencia") == 0) {
            try {
                clases.EliminarEntrega eliEnt=new clases.EliminarEntrega();
                eliEnt.eliminarEntrega();
            } catch (IOException ex) {
                Logger.getLogger(DialogoNuevaRecepcion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogoTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogoTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogoTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogoTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogoTransferencia dialog = new DialogoTransferencia(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboBloqueDestino;
    private javax.swing.JComboBox cboBloqueOrigen;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdSeleccionarItemDestino;
    private javax.swing.JButton cmdSeleccionarItemOrigen;
    private javax.swing.JButton cmdSeleccionarMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoItemDestino;
    private javax.swing.JTextField txtCodigoItemOrigen;
    private javax.swing.JTextField txtContratistaDestino;
    private javax.swing.JTextField txtContratistaOrigen;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtMaterial;
    private javax.swing.JTextField txtNombreItemDestino;
    private javax.swing.JTextField txtNombreItemOrigen;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables
}
