/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kaze
 */
public class FormularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
//        this.setExtendedState(MAXIMIZED_BOTH);
//        this.setLayout(new FlowLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdControlMaterial = new javax.swing.JButton();
        cmdComprobarStock = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuAlmacenes = new javax.swing.JMenu();
        mnuNuevaRecepcion = new javax.swing.JMenuItem();
        mnuVerRecepciones = new javax.swing.JMenuItem();
        mnuNuevaEntrega = new javax.swing.JMenuItem();
        mnuVerEntregas = new javax.swing.JMenuItem();
        mnuNuevaTransferencia = new javax.swing.JMenuItem();
        mnuVerTransferencias = new javax.swing.JMenuItem();
        mnuContratistas = new javax.swing.JMenu();
        mnuNuevoContratísta = new javax.swing.JMenuItem();
        mnuVerContratistas = new javax.swing.JMenuItem();
        mnuControl = new javax.swing.JMenu();
        mnuControlMaterial = new javax.swing.JMenuItem();
        mnuStock = new javax.swing.JMenu();
        mnuComprobarStock = new javax.swing.JMenuItem();
        mnuMinimos = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuGenerarItems = new javax.swing.JMenuItem();
        mnuGenerarMateriales = new javax.swing.JMenuItem();
        mnuSubirFTP = new javax.swing.JMenuItem();
        mnuBajarFTP = new javax.swing.JMenuItem();
        mnuAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Software de Gestión de Construcción Masiva");
        setResizable(false);

        cmdControlMaterial.setText("Control de Materiales");
        cmdControlMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdControlMaterialActionPerformed(evt);
            }
        });

        cmdComprobarStock.setText("Comprobar Stock");
        cmdComprobarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdComprobarStockActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Logo_Sokolmet.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        mnuAlmacenes.setText("Almacenes");

        mnuNuevaRecepcion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, 0));
        mnuNuevaRecepcion.setText("Nueva Recepción");
        mnuNuevaRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaRecepcionActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuNuevaRecepcion);

        mnuVerRecepciones.setText("Ver Recepciones");
        mnuVerRecepciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerRecepcionesActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuVerRecepciones);

        mnuNuevaEntrega.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, 0));
        mnuNuevaEntrega.setText("Nueva Entrega");
        mnuNuevaEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaEntregaActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuNuevaEntrega);

        mnuVerEntregas.setText("Ver Entregas");
        mnuVerEntregas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerEntregasActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuVerEntregas);

        mnuNuevaTransferencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        mnuNuevaTransferencia.setText("Nueva Transferencia");
        mnuNuevaTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevaTransferenciaActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuNuevaTransferencia);

        mnuVerTransferencias.setText("Ver Transferencias");
        mnuVerTransferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVerTransferenciasActionPerformed(evt);
            }
        });
        mnuAlmacenes.add(mnuVerTransferencias);

        jMenuBar1.add(mnuAlmacenes);

        mnuContratistas.setText("Contratístas");

        mnuNuevoContratísta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        mnuNuevoContratísta.setText("Asignar un Contratísta a un Bloque");
        mnuNuevoContratísta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNuevoContratístaActionPerformed(evt);
            }
        });
        mnuContratistas.add(mnuNuevoContratísta);

        mnuVerContratistas.setText("Ver Contratístas");
        mnuContratistas.add(mnuVerContratistas);

        jMenuBar1.add(mnuContratistas);

        mnuControl.setText("Control de...");

        mnuControlMaterial.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        mnuControlMaterial.setText("Control de materiales");
        mnuControlMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuControlMaterialActionPerformed(evt);
            }
        });
        mnuControl.add(mnuControlMaterial);

        jMenuBar1.add(mnuControl);

        mnuStock.setText("Stock");

        mnuComprobarStock.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, 0));
        mnuComprobarStock.setText("Comprobar Stock");
        mnuComprobarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComprobarStockActionPerformed(evt);
            }
        });
        mnuStock.add(mnuComprobarStock);

        mnuMinimos.setText("Ajustar mínimos de stock de materiales");
        mnuMinimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMinimosActionPerformed(evt);
            }
        });
        mnuStock.add(mnuMinimos);

        jMenuBar1.add(mnuStock);

        mnuAyuda.setText("Ayuda");

        mnuGenerarItems.setText("Generar lista de Items");
        mnuGenerarItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarItemsActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuGenerarItems);

        mnuGenerarMateriales.setText("Generar lista de materiales");
        mnuGenerarMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGenerarMaterialesActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuGenerarMateriales);

        mnuSubirFTP.setText("Hacer copia de seguridad");
        mnuSubirFTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSubirFTPActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuSubirFTP);

        mnuBajarFTP.setText("Descargar copia del Servidor");
        mnuBajarFTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBajarFTPActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuBajarFTP);

        mnuAcercaDe.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, 0));
        mnuAcercaDe.setText("Acerca de...");
        mnuAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAcercaDeActionPerformed(evt);
            }
        });
        mnuAyuda.add(mnuAcercaDe);

        jMenuBar1.add(mnuAyuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdComprobarStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdControlMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmdControlMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdComprobarStock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAcercaDeActionPerformed
        DialogoAcercaDe Acerca = new DialogoAcercaDe(null,true);
        Acerca.setVisible(true);
    }//GEN-LAST:event_mnuAcercaDeActionPerformed

    private void mnuNuevaRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaRecepcionActionPerformed
        clases.SOGECOMA.cargarDatos=false;
        DialogoNuevaRecepcion NuevaRec = new DialogoNuevaRecepcion(null,true);
        NuevaRec.setVisible(true);
    }//GEN-LAST:event_mnuNuevaRecepcionActionPerformed

    private void mnuNuevaEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaEntregaActionPerformed
        clases.SOGECOMA.cargarDatos=false;
        DialogoNuevaEntrega NuevaEnt = new DialogoNuevaEntrega(null,true);
        NuevaEnt.setVisible(true);
    }//GEN-LAST:event_mnuNuevaEntregaActionPerformed

    private void mnuNuevoContratístaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevoContratístaActionPerformed
        clases.SOGECOMA.cargarDatos=false;
        DialogoNuevoContratista NuevoCont = new DialogoNuevoContratista(null,true);
        NuevoCont.setVisible(true);
    }//GEN-LAST:event_mnuNuevoContratístaActionPerformed

    private void mnuGenerarMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarMaterialesActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Esta tarea solo debe realizarse al iniciar un proyecto\no si la lista de materiales oficial ha sido modificada, ¿Continuar?")==0){
            try {
                clases.GenerarMateriales genMat = new clases.GenerarMateriales();
                genMat.generadorMateriales();
            } catch (IOException ex) {
                Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuGenerarMaterialesActionPerformed

    private void mnuGenerarItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGenerarItemsActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Esta tarea solo debe realizarse al iniciar un proyecto\no si la lista de items oficial ha sido modificada, ¿Continuar?")==0){  
            try {
                clases.GenerarItems genIt = new clases.GenerarItems();
                genIt.generadorItems();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_mnuGenerarItemsActionPerformed

    private void cmdControlMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdControlMaterialActionPerformed
        DialogoControlMaterial verMat=new DialogoControlMaterial(null,true);
        verMat.setVisible(true);
    }//GEN-LAST:event_cmdControlMaterialActionPerformed

    private void mnuControlMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuControlMaterialActionPerformed
        DialogoControlMaterial verMat=new DialogoControlMaterial(null,true);
        verMat.setVisible(true);
    }//GEN-LAST:event_mnuControlMaterialActionPerformed

    private void cmdComprobarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdComprobarStockActionPerformed
        try {
            DialogoStock diaStk=new DialogoStock(null,true);
            diaStk.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdComprobarStockActionPerformed

    private void mnuComprobarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComprobarStockActionPerformed
        try {
            DialogoStock diaStk=new DialogoStock(null,true);
            diaStk.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(FormularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnuComprobarStockActionPerformed

    private void mnuMinimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMinimosActionPerformed
        DialogoMinimos diaMin=new DialogoMinimos(null,true);
        diaMin.setVisible(true);
    }//GEN-LAST:event_mnuMinimosActionPerformed

    private void mnuBajarFTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBajarFTPActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Esta acción sobreescribirá el archivo SOGECOMA.xls de SU EQUIPO, ¿Continuar?")==0){
                clases.SOGECOMA.bajarArchivoPorFTP("SOGECOMA.xls");
            }
    }//GEN-LAST:event_mnuBajarFTPActionPerformed

    private void mnuSubirFTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSubirFTPActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Esta acción sobreescribirá el archivo SOGECOMA.xls DEL SERVIDOR, ¿Continuar?")==0){
                clases.SOGECOMA.subirArchivoPorFTP();
            }
    }//GEN-LAST:event_mnuSubirFTPActionPerformed

    private void mnuVerRecepcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerRecepcionesActionPerformed
        try {
            clases.SOGECOMA.RoE=true;//Es Recepcion.
            ventanas.DialogoVerER verER=new ventanas.DialogoVerER(null, true);
            verER.setVisible(true);
        }catch(Exception e){}
    }//GEN-LAST:event_mnuVerRecepcionesActionPerformed

    private void mnuVerEntregasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerEntregasActionPerformed
        try {
            clases.SOGECOMA.RoE=false;//Es Entrega.
            ventanas.DialogoVerER verER=new ventanas.DialogoVerER(null, true);
            verER.setVisible(true);
        }catch(Exception e){}
    }//GEN-LAST:event_mnuVerEntregasActionPerformed

    private void mnuVerTransferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVerTransferenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuVerTransferenciasActionPerformed

    private void mnuNuevaTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNuevaTransferenciaActionPerformed
       DialogoTransferencia diaTrans = new DialogoTransferencia(null, true);
       diaTrans.setVisible(true);
    }//GEN-LAST:event_mnuNuevaTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdComprobarStock;
    private javax.swing.JButton cmdControlMaterial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAcercaDe;
    private javax.swing.JMenu mnuAlmacenes;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuItem mnuBajarFTP;
    private javax.swing.JMenuItem mnuComprobarStock;
    private javax.swing.JMenu mnuContratistas;
    private javax.swing.JMenu mnuControl;
    private javax.swing.JMenuItem mnuControlMaterial;
    private javax.swing.JMenuItem mnuGenerarItems;
    private javax.swing.JMenuItem mnuGenerarMateriales;
    private javax.swing.JMenuItem mnuMinimos;
    private javax.swing.JMenuItem mnuNuevaEntrega;
    private javax.swing.JMenuItem mnuNuevaRecepcion;
    private javax.swing.JMenuItem mnuNuevaTransferencia;
    private javax.swing.JMenuItem mnuNuevoContratísta;
    private javax.swing.JMenu mnuStock;
    private javax.swing.JMenuItem mnuSubirFTP;
    private javax.swing.JMenuItem mnuVerContratistas;
    private javax.swing.JMenuItem mnuVerEntregas;
    private javax.swing.JMenuItem mnuVerRecepciones;
    private javax.swing.JMenuItem mnuVerTransferencias;
    // End of variables declaration//GEN-END:variables
}
