/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaze
 */
public class PanelComparativaConsumo extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuscarItem
     */
    public PanelComparativaConsumo() {
        initComponents();
        clases.SOGECOMA.ModeloTablaBuscarItem.setRowCount(0);
        clases.SOGECOMA.ModeloTablaBuscarItem.setColumnCount(0);
        tablaComparativaConsumo.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
        clases.FormatearTablas forTab=new clases.FormatearTablas();
        forTab.formatearTablaBuscarItem();
        tablaComparativaConsumo.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComparativaConsumo = new javax.swing.JTable();
        cmdSeleccionarItem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoItem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreItem = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Comparativa de consumo de material entre bloques, por ítem:");

        tablaComparativaConsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaComparativaConsumo);

        cmdSeleccionarItem.setText("Seleccionar Ítem");
        cmdSeleccionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarItemActionPerformed(evt);
            }
        });

        jLabel11.setText("Ítem:");

        txtCodigoItem.setEditable(false);

        jLabel12.setText("Nombre del Ítem:");

        txtNombreItem.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85)
                        .addComponent(cmdSeleccionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 95, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtNombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdSeleccionarItem))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSeleccionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarItemActionPerformed
        try {
            DialogoSelectorItem selIt = new DialogoSelectorItem(null,true);
            selIt.setVisible(true);
            txtNombreItem.setText(clases.SOGECOMA.nomItem);
            txtCodigoItem.setText(clases.SOGECOMA.numItem);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
        clases.SOGECOMA.ModeloTablaComparativaConsumo.setRowCount(0);
        clases.SOGECOMA.ModeloTablaComparativaConsumo.setColumnCount(0);
        tablaComparativaConsumo.setModel(clases.SOGECOMA.ModeloTablaComparativaConsumo);
        clases.CargarTablas carTab=new clases.CargarTablas();
        try {
            carTab.cargarTablaComparativaConsumo(txtCodigoItem.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        }

        tablaComparativaConsumo.setModel(clases.SOGECOMA.ModeloTablaComparativaConsumo);
        
    }//GEN-LAST:event_cmdSeleccionarItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdSeleccionarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaComparativaConsumo;
    private javax.swing.JTextField txtCodigoItem;
    private javax.swing.JTextField txtNombreItem;
    // End of variables declaration//GEN-END:variables
}
