/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kaze
 */
public class PanelBuscarItem extends javax.swing.JPanel {

    /**
     * Creates new form PanelBuscarItem
     */
    public PanelBuscarItem() {
        initComponents();
        clases.SOGECOMA.ModeloTablaBuscarItem.setRowCount(0);
        clases.SOGECOMA.ModeloTablaBuscarItem.setColumnCount(0);
        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
        clases.FormatearTablas forTab=new clases.FormatearTablas();
        forTab.formatearTablaBuscarItem();
        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBuscarItem = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cboBloque = new javax.swing.JComboBox();
        cmdSeleccionarItem = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCodigoItem = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNombreItem = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Materiales entregados por ítem de un bloque:");

        tablaBuscarItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaBuscarItem);

        jLabel9.setText("Seleccione el bloque a consultar:");

        cboBloque.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "Ñ", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "AA", "BB", "CC", "DD", "EE", "FF", "GG", "HH" }));
        cboBloque.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cboBloquePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cmdSeleccionarItem.setText("Seleccionar Ítem");
        cmdSeleccionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSeleccionarItemActionPerformed(evt);
            }
        });

        jLabel11.setText("Ítem:");

        txtCodigoItem.setEditable(false);

        jLabel12.setText("Nombre del Ítem:");

        txtNombreItem.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1048, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSeleccionarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreItem, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboBloque, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtNombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cboBloque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtCodigoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmdSeleccionarItem))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboBloquePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cboBloquePopupMenuWillBecomeInvisible
        clases.SOGECOMA.ModeloTablaBuscarItem.setRowCount(0);
        clases.SOGECOMA.ModeloTablaBuscarItem.setColumnCount(0);
        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
        clases.CargarTablas carTab=new clases.CargarTablas();
        try {
            carTab.cargarTablaBuscarItem(cboBloque.getSelectedItem().toString(),txtCodigoItem.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        }

        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
    }//GEN-LAST:event_cboBloquePopupMenuWillBecomeInvisible

    private void cmdSeleccionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSeleccionarItemActionPerformed
        try {
            DialogoSelectorItem selIt = new DialogoSelectorItem(null,true);
            selIt.setVisible(true);
            txtNombreItem.setText(clases.SOGECOMA.nomItem);
            txtCodigoItem.setText(clases.SOGECOMA.numItem);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DialogoNuevaEntrega.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!cboBloque.getSelectedItem().toString().equals(" ")){
            clases.SOGECOMA.ModeloTablaBuscarItem.setRowCount(0);
        clases.SOGECOMA.ModeloTablaBuscarItem.setColumnCount(0);
        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
        clases.CargarTablas carTab=new clases.CargarTablas();
        try {
            carTab.cargarTablaBuscarItem(cboBloque.getSelectedItem().toString(),txtCodigoItem.getText());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PanelTodosItems.class.getName()).log(Level.SEVERE, null, ex);
        }

        tablaBuscarItem.setModel(clases.SOGECOMA.ModeloTablaBuscarItem);
        }
    }//GEN-LAST:event_cmdSeleccionarItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboBloque;
    private javax.swing.JButton cmdSeleccionarItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBuscarItem;
    private javax.swing.JTextField txtCodigoItem;
    private javax.swing.JTextField txtNombreItem;
    // End of variables declaration//GEN-END:variables
}
